logging:
  level:
    # org.springframework.web: DEBUG
    org.springframework: DEBUG
    elr.ws.elrws: DEBUG

server:
    port: 8888
    servlet:
      context-path: /elrservice

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

